### ISSUE TITLE
Highlight Voting Time

### ISSUE THREAD

**Issue by sirnicolaz** [solidato/dapp#12]
Text related to voting gets missed in the page, particularly for someone that is using the dapp for the first time.

I would suggest to make it more clear that there is a voting countdown both on the main list (imagine a new user that creates a resolution and needs to immediately understand that in 2 minutes he will have to vote) and also in the resolution page (same: as soon as the user enters, it needs to be crystal clear that there is a voting countdown)

<img width="410" alt="Screenshot 2024-06-04 at 14 37 44" src="https://github.com/solidato/dapp/assets/936916/0ef50c73-f409-44e1-ad3b-a9807e1bdcba">

<img width="1378" alt="Screenshot 2024-06-04 at 14 37 28" src="https://github.com/solidato/dapp/assets/936916/2efd04d2-66de-45ef-b4ee-90e64d4f4e6d">

**Comment by stecb** [comment]
@sirnicolaz You posted a problem without proposing a solution: how would you fix it? What text would you write?

**Comment by sirnicolaz** [comment]
do you have an idea? i could propose to use a bigger font and a more impactful color, but with UI related stuff things always are different in my head then in reality... so if you have some ideas feel free to just give it a go

**Comment by stecb** [comment]
done, please check if you like it
