### ISSUE TITLE
Confusing resolution tags

### ISSUE THREAD

**Issue by sirnicolaz** [solidato/dapp#13]
This tags carry no informative value, as they use the internal naming of the resolutions.

Either map them to something more meaningful, or better remove them completely.

<img width="263" alt="Screenshot 2024-06-04 at 14 36 58" src="https://github.com/solidato/dapp/assets/936916/2a77c74f-0f50-42e5-a1f0-e889f49af233">

**Comment by stecb** [comment]
Again, you're telling the problem without proposing anything valuable: Would you have a list of meaningful names to map to?

**Comment by sirnicolaz** [comment]
yeah, a list of meaningul names would be better, maybe just using the names we have in the list when you create the resolution.

**Comment by stecb** [comment]
Fixed. Used the names we have in the list
