### ISSUE TITLE
Resolution not appearing in list right after creation

### ISSUE THREAD

**Issue by sirnicolaz** [solidato/dapp#14]
It already happened a couple of times in a non reproduceable fashion: I created a resolution, it was immediately confirmed,and once I was on the list page, it was not there. I had to refresh manually in order to see it. Is there anyway we can be more robust and defensive there? like always polling? at least for the demo

**Comment by sirnicolaz** [comment]
lower time might just do the trick

**Comment by stecb** [comment]
Lowered + hide resolutions <= id 9
